server:
  port: 8080
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: op-gateway
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.130:8848
      config:
        server-addr: 192.168.88.130:8848
    gateway:
      routes:
        - id: deepseek # 路由规则id，自定义，唯一
          uri: lb://model-proxy-deepseek # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/deepseek/** # 这里是以请求路径作为判断规则
        - id: glm4
          uri: lb://model-proxy-glm4
          predicates:
            - Path=/glm4/**
        - id: orchestrator
          uri: lb://orchestrator-service
          predicates:
            - Path=/orchestrator/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
      default-filters:
        - AddRequestHeader=truth, Just do it!!!!!
  rabbitmq:
    host: 192.168.88.130
    port: 5672
    virtual-host: /op
    username: op
    password: 123456
op:
  auth:
    excludePaths:
      - /user/code
      - /user/login