server:
  port: 8081
spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${op.db.host}:3306/aimodel-orchestration-platform?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${op.db.pw}
  redis:
    host: 192.168.88.130
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.130:8848
      config:
        server-addr: 192.168.88.130:8848
    sentinel:
      transport:
        dashboard: localhost:8090
  main:
    allow-circular-references: true
  rabbitmq:
    host: 192.168.88.130
    port: 5672
    virtual-host: /op
    username: op
    password: 123456
#开启okhttp功能
feign:
  okhttp:
    enabled: true